### ISSUE TITLE
公钥和csrf

### ISSUE THREAD

**Issue by Mashiro2000** [gphwxhq/yiban#1]
请问下，公钥和csrf要怎么获取呢，反编译吗

**Comment by gphwxhq** [comment]
> 
> 
> 请问下，公钥和csrf要怎么获取呢，反编译吗

公钥要解安装包，csrf随便生成就行，今天更新以后公钥已经换了

**Comment by Mashiro2000** [comment]
> > 请问下，公钥和csrf要怎么获取呢，反编译吗
> 
> 公钥要解安装包，csrf随便生成就行，今天更新以后公钥已经换了

之前用v3接口，不需要加密，现在换成v4接口，需要公钥，想要请教下，反编译apk后，一般公钥会放在哪一个文件里，

**Comment by gphwxhq** [comment]
> 
> 
> > > 请问下，公钥和csrf要怎么获取呢，反编译吗
> > 
> > 
> > 公钥要解安装包，csrf随便生成就行，今天更新以后公钥已经换了
> 
> 之前用v3接口，不需要加密，现在换成v4接口，需要公钥，想要请教下，反编译apk后，一般公钥会放在哪一个文件里，
解包我也没解过，如果你能绕过加的壳的话搜索一下应该就行

**Comment by gphwxhq** [comment]
> 
> 
> > > 请问下，公钥和csrf要怎么获取呢，反编译吗
> > 
> > 
> > 公钥要解安装包，csrf随便生成就行，今天更新以后公钥已经换了
> 
> 之前用v3接口，不需要加密，现在换成v4接口，需要公钥，想要请教下，反编译apk后，一般公钥会放在哪一个文件里，

解包我也没解过，如果你能绕过加壳的话搜索一下应该就行，主要难度在它加壳了

**Comment by Mashiro2000** [comment]
> > > > 请问下，公钥和csrf要怎么获取呢，反编译吗
> > > 
> > > 
> > > 公钥要解安装包，csrf随便生成就行，今天更新以后公钥已经换了
> > 
> > 
> > 之前用v3接口，不需要加密，现在换成v4接口，需要公钥，想要请教下，反编译apk后，一般公钥会放在哪一个文件里，
> 
> 解包我也没解过，如果你能绕过加壳的话搜索一下应该就行，主要难度在它加壳了

好的，

**Comment by asjdf** [comment]
如果大佬拿到公钥的话踢一下我，非常感谢

**Comment by Err0rCM** [comment]
大佬好！今日更新使用了v4接口，发现总是会提示版本过低，这是我的header和响应message，请问大佬开发中有遇到这样的问题吗？
```
{
'Origin': 'https://mobile.yiban.cn', 
'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
'Referer': 'https://mobile.yiban.cn',
 'AppVersion': '5.0'
}
您的客户端版本太低，请到易班官网下载最新版本[2]
```
尤其是这个[2]，加了AppVersion这一项就变成2了，原来是1
这是请求参数
```
params = {
            "mobile": self.account,
            "password": self.encrypt_passwd(self.passwd),
            "imei": "0",
            "ct": "2",  # 更新内容 1或者2 暂不清楚什么用，硬解码为2
            "identify": "360933077266594",  # 更新内容 确认为手机的IEMI码
            "v": "5.0",
            "device": "vivo AV1938T",
            "sig": "5692393ff332462c",
            "sversion": "25",
            "apn": "wifi",
            "token": "",
            "app": "1",
            "authCode": ""
        }
```

**Comment by gphwxhq** [comment]
> 大佬好！今日更新使用了v4接口，发现总是会提示版本过低，这是我的header和响应message，请问大佬开发中有遇到这样的问题吗？
> 
> ```
> {
> 'Origin': 'https://mobile.yiban.cn', 
> 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> 'Referer': 'https://mobile.yiban.cn',
>  'AppVersion': '5.0'
> }
> 您的客户端版本太低，请到易班官网下载最新版本[2]
> ```
> 
> 尤其是这个[2]，加了AppVersion这一项就变成2了，原来是1
> 这是请求参数
> 
> ```
> params = {
>             "mobile": self.account,
>             "password": self.encrypt_passwd(self.passwd),
>             "imei": "0",
>             "ct": "2",  # 更新内容 1或者2 暂不清楚什么用，硬解码为2
>             "identify": "360933077266594",  # 更新内容 确认为手机的IEMI码
>             "v": "5.0",
>             "device": "vivo AV1938T",
>             "sig": "5692393ff332462c",
>             "sversion": "25",
>             "apn": "wifi",
>             "token": "",
>             "app": "1",
>             "authCode": ""
>         }
> ```

是密码的问题，加密的公钥换了，如果它不能解密就会报这个

**Comment by 123cdxcc** [comment]
公钥在os文件里，我反编译os没发现，然后用frida hook了获取公钥的方法，也获取不到，太神奇了
